name: voting-app
replicaCount: 1

image: dockersamples/examplevotingapp_vote:before
dockercfg: null

service:
  type: LoadBalancer
  port: 80

pullPolicy: Always

env:
  config:
    REDIS_HOST: redis
    REDIS_PORT: "6379"
  secrets:
    REDIS_PASSWORD: redispassword789