name: my-app
replicaCount: 2

image: <+artifacts.primary.image>
dockercfg: <+artifacts.primary.imagePullSecret>

createNamespace: true
namespace: <+infra.namespace>

service:
  type: LoadBalancer
  port: 80

pullPolicy: IfNotPresent

env:
  config:
    key1: value1
  secrets:
    key2: value2