{{- range $key, $svc := .Values.microservices }}
{{- if $svc.env.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $svc.name }}
  labels:
    app: {{ $svc.name }}
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    release: {{ $.Release.Name }}
    harness.io/release-name: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
type: Opaque
stringData:
{{- range $key, $value := $svc.env.secrets }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
---
{{- end }}
{{- end }}
