{{- range .Values.uis }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
    tier: frontend
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
        tier: frontend
    spec:
      containers:
        - name: {{ .name }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          ports:
            - containerPort: {{ .containerPort }}

          {{- if .env }}
          env:
            {{- range $key, $val := .env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          {{- end }}

          {{- if or .envFromConfigMap .envFromSecret }}
          envFrom:
            {{- if .envFromConfigMap }}
            - configMapRef:
                name: {{ .envFromConfigMap }}
            {{- end }}
            {{- if .envFromSecret }}
            - secretRef:
                name: {{ .envFromSecret }}
            {{- end }}
          {{- end }}

          resources:
            {{- toYaml .resources | nindent 12 }}
{{- end }}