{{- range $key, $svc := .Values.microservices }}
{{- if $svc.env.config }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $svc.name }}
  labels:
    app: {{ $svc.name }}
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    release: "{{ $.Release.Name }}"
    harness.io/release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  replicas: {{ $svc.replicaCount }}
  selector:
    matchLabels:
      app: {{ $svc.name }}
      release: {{ $.Release.Name }}
  template:
    metadata:
      labels:
        app: {{ $svc.name }}
        release: {{ $.Release.Name }}
        harness.io/release: {{ $.Release.Name }}
    spec:
      {{- if $svc.dockercfg }}
      imagePullSecrets:
        - name: {{ $svc.name }}-dockercfg
      {{- end }}
      containers:
        - name: {{ $svc.name }}
          image: {{ $svc.image }}
          imagePullPolicy: {{ $svc.pullPolicy }}
          ports:
            - containerPort: {{ $svc.service.port }}
              protocol: TCP
              name: http
          {{- if or $svc.env.config $svc.env.secrets }}
          envFrom:
            {{- if $svc.env.config }}
            - configMapRef:
                name: {{ $svc.name }}
            {{- end }}
            {{- if $svc.env.secrets }}
            - secretRef:
                name: {{ $svc.name }}
            {{- end }}
          {{- end }}
---
{{- end }}
{{- end }}