{{- if .Values.apps.vote.enabled }}
{{- if .Values.apps.vote.env.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.apps.vote.name }}
stringData:
{{ .Values.apps.vote.env.secrets | toYaml | indent 2 }}
---
{{- end }}
{{- end }}

{{- if .Values.apps.worker.enabled }}
{{- if .Values.apps.worker.env.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.apps.worker.name }}
stringData:
{{ .Values.apps.worker.env.secrets | toYaml | indent 2 }}
---
{{- end }}
{{- end }}