{{- if .Values.apps.vote.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apps.vote.name }}
  labels:
    app: {{ .Values.apps.vote.name }}
    component: vote
    chart: {{ template "todolist.chart" . }}
    release: {{ .Release.Name }}
    harness.io/release-name: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.apps.vote.service.type }}
  ports:
    - port: {{ .Values.apps.vote.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.apps.vote.name }}
    component: vote
    release: {{ .Release.Name }}
---
{{- end }}

{{- if .Values.apps.result.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apps.result.name }}
  labels:
    app: {{ .Values.apps.result.name }}
    component: result
    chart: {{ template "todolist.chart" . }}
    release: {{ .Release.Name }}
    harness.io/release-name: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.apps.result.service.type }}
  ports:
    - port: {{ .Values.apps.result.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.apps.result.name }}
    component: result
    release: {{ .Release.Name }}
---
{{- end }}

{{- if .Values.apps.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apps.redis.name }}
  labels:
    app: {{ .Values.apps.redis.name }}
    component: redis
    chart: {{ template "todolist.chart" . }}
    release: {{ .Release.Name }}
    harness.io/release-name: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.apps.redis.service.type }}
  ports:
    - port: {{ .Values.apps.redis.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    app: {{ .Values.apps.redis.name }}
    component: redis
    release: {{ .Release.Name }}
---
{{- end }}